const hotelList = [
  {
    id: "grand-palais",
    name: "The Grand Palais",
    location: "Paris, France",
    locationSearch: "paris france",
    price: 320,
    stars: 5,
    rating: 9.4,
    ratingLabel: "Exceptional",
    reviews: 124,
    badge: "Featured",
    types: ["boutique"],
    amenities: ["pool", "spa", "gym", "restaurant"],
    img: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=90",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=90",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=90",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=90",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=90",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=90",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=90",
    ],
    address: "8 Rue de Rivoli, 75001 Paris, France",
    description: [
      "Nestled in the heart of Paris along the iconic Rue de Rivoli, The Grand Palais is a timeless sanctuary of elegance and French art de vivre. Built in 1887 and meticulously restored, this palatial property blends Belle Époque grandeur with contemporary luxury.",
      "Each of our 142 rooms and suites has been individually designed by renowned Parisian interior architect Sophie Marchand, featuring hand-woven silk draperies, custom furnishings, and breathtaking views of the Tuileries Garden or the Louvre.",
      "Our Michelin-starred restaurant, Le Jardin d'Or, offers an extraordinary culinary journey through seasonal French cuisine, while our rooftop bar provides the most spectacular sunsets over the Eiffel Tower.",
    ],
    rooms: [
      {
        name: "Deluxe Room",
        size: "30 m²",
        view: "Garden View",
        bed: "King Bed",
        price: 320,
        breakfast: "Breakfast optional",
        img: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=400&q=80",
        badge: "",
      },
      {
        name: "Junior Suite",
        size: "55 m²",
        view: "Eiffel Tower View",
        bed: "King Bed",
        price: 540,
        breakfast: "Breakfast included",
        img: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&q=80",
        badge: "",
      },
      {
        name: "Presidential Suite",
        size: "180 m²",
        view: "Panoramic View",
        bed: "2 Bedrooms",
        price: 1200,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Marble Bathroom",
      '65" Smart TV',
      "Nespresso",
      "Climate Control",
      "In-room Safe",
      "Turndown Service",
      "L'Occitane Toiletries",
      "Minibar",
    ],
    hotelFacilities: [
      "Rooftop Pool",
      "Spa & Wellness",
      "Fitness Centre",
      "Michelin Restaurant",
      "Rooftop Bar",
      "Valet Parking",
      "Airport Transfer",
      "Pet Friendly",
    ],
    nearbyPois: [
      { icon: "✈️", name: "CDG Airport", time: "35 min by car" },
      { icon: "🗼", name: "Eiffel Tower", time: "12 min walk" },
      { icon: "🏛", name: "The Louvre", time: "3 min walk" },
    ],
    checkin: "From 3:00 PM",
    checkout: "Until 12:00 PM",
    reviewsList: [
      {
        name: "Sarah Mitchell",
        date: "May 2025 · Junior Suite",
        avatar: "https://i.pravatar.cc/80?img=47",
        stars: 5,
        text: "Absolutely magnificent. The suite had views that made us gasp every morning. Service was personal, warm and incredibly attentive without being intrusive.",
      },
      {
        name: "James Keller",
        date: "April 2025 · Deluxe Room",
        avatar: "https://i.pravatar.cc/80?img=12",
        stars: 5,
        text: "The dinner at Le Jardin d'Or was one of the most extraordinary culinary experiences of my life. The sommelier's pairings were inspired. We'll be back.",
      },
    ],
    scores: { cleanliness: 9.6, location: 9.8, service: 9.2, value: 8.8 },
  },
  {
    id: "villa-santorini",
    name: "Villa Santorini Blue",
    location: "Santorini, Greece",
    locationSearch: "santorini greece",
    price: 480,
    stars: 5,
    rating: 9.7,
    ratingLabel: "Exceptional",
    reviews: 89,
    badge: "New",
    types: ["villa"],
    amenities: ["pool", "spa", "restaurant", "beach"],
    img: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=90",
      "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=1200&q=90",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=90",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=90",
    ],
    address: "Oia, Santorini 847 02, Greece",
    description: [
      "Perched on the volcanic caldera cliffs of Oia, Villa Santorini Blue offers an unparalleled escape into the iconic Cycladic world. Dazzling whitewashed architecture, infinite blue domes, and views that define the Greek island dream.",
      "Each villa suite features a private infinity pool terrace overlooking the caldera, handcrafted local furniture, and open-air living spaces bathed in the golden Aegean light.",
    ],
    rooms: [
      {
        name: "Caldera Suite",
        size: "60 m²",
        view: "Caldera View",
        bed: "King Bed",
        price: 480,
        breakfast: "Breakfast included",
        img: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&q=80",
        badge: "",
      },
      {
        name: "Cave Pool Villa",
        size: "100 m²",
        view: "Infinity Pool & Caldera",
        bed: "King Bed + Sofa",
        price: 890,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Outdoor Jacuzzi",
      "Smart TV",
      "Nespresso",
      "Climate Control",
      "Luxury Toiletries",
      "Welcome Champagne",
    ],
    hotelFacilities: [
      "Infinity Pool",
      "Spa",
      "Caldera Restaurant",
      "Sunset Bar",
      "Airport Transfer",
      "Boat Tours",
    ],
    nearbyPois: [
      { icon: "🌅", name: "Oia Sunset Point", time: "5 min walk" },
      { icon: "⛵", name: "Amoudi Bay", time: "10 min walk" },
      { icon: "✈️", name: "Santorini Airport", time: "30 min by car" },
    ],
    checkin: "From 3:00 PM",
    checkout: "Until 11:00 AM",
    reviewsList: [
      {
        name: "Mei Lin",
        date: "April 2025 · Caldera Suite",
        avatar: "https://i.pravatar.cc/80?img=32",
        stars: 5,
        text: "The most breathtaking place I have ever stayed. Waking up to that view every morning felt unreal. The staff made us feel like royalty.",
      },
    ],
    scores: { cleanliness: 9.8, location: 9.9, service: 9.6, value: 9.2 },
  },
  {
    id: "kyoto-zen",
    name: "Kyoto Zen Retreat",
    location: "Kyoto, Japan",
    locationSearch: "kyoto japan",
    price: 265,
    stars: 4,
    rating: 9.1,
    ratingLabel: "Superb",
    reviews: 211,
    badge: "",
    types: ["retreat"],
    amenities: ["spa", "restaurant", "gym"],
    img: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=90",
      "https://images.unsplash.com/photo-1536625979259-e8d0d612f88d?w=1200&q=90",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=90",
    ],
    address: "12 Higashiyama-ku, Kyoto 605-0000, Japan",
    description: [
      "Nestled among bamboo groves in Higashiyama, Kyoto Zen Retreat is a celebration of wabi-sabi — the Japanese philosophy of beauty in imperfection. A 300-year-old machiya townhouse transformed into a sanctuary of stillness.",
      "Guests are invited to participate in morning tea ceremonies, ikebana flower arranging, and guided zazen meditation sessions led by resident monks.",
    ],
    rooms: [
      {
        name: "Garden Room",
        size: "28 m²",
        view: "Zen Garden",
        bed: "Futon Bed",
        price: 265,
        breakfast: "Kaiseki breakfast",
        img: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400&q=80",
        badge: "",
      },
      {
        name: "Tatami Suite",
        size: "48 m²",
        view: "Maple Garden",
        bed: "Futon + Sofa",
        price: 420,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Hinoki Wood Bath",
      "Matcha Tea Set",
      "Underfloor Heating",
      "Kinokuniya Toiletries",
      "Yukata Robes",
    ],
    hotelFacilities: [
      "Onsen Spa",
      "Kaiseki Restaurant",
      "Meditation Hall",
      "Zen Garden",
      "Bicycle Rental",
    ],
    nearbyPois: [
      { icon: "⛩️", name: "Fushimi Inari", time: "15 min by bus" },
      { icon: "🌸", name: "Maruyama Park", time: "8 min walk" },
      { icon: "✈️", name: "Osaka KIX Airport", time: "75 min by train" },
    ],
    checkin: "From 4:00 PM",
    checkout: "Until 11:00 AM",
    reviewsList: [
      {
        name: "Elena Rossi",
        date: "March 2025 · Tatami Suite",
        avatar: "https://i.pravatar.cc/80?img=25",
        stars: 5,
        text: "An authentic, deeply peaceful experience. The morning tea ceremony changed my perspective on slowness. Absolutely unmissable in Kyoto.",
      },
    ],
    scores: { cleanliness: 9.4, location: 8.9, service: 9.3, value: 9.5 },
  },
  {
    id: "amalfi-cliffside",
    name: "Amalfi Cliffside Resort",
    location: "Amalfi, Italy",
    locationSearch: "amalfi italy",
    price: 590,
    stars: 5,
    rating: 9.5,
    ratingLabel: "Exceptional",
    reviews: 67,
    badge: "Popular",
    types: ["resort"],
    amenities: ["pool", "spa", "restaurant", "beach", "gym"],
    img: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=90",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=90",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=90",
    ],
    address: "Via Pantaleone Comite 1, 84011 Amalfi SA, Italy",
    description: [
      "Dramatically carved into the limestone cliffs of the Amalfi Coast, this legendary resort is a hymn to Italian la dolce vita. Terraced gardens cascade to a private beach, while the crystalline Tyrrhenian Sea stretches endlessly before you.",
    ],
    rooms: [
      {
        name: "Sea View Room",
        size: "35 m²",
        view: "Sea View",
        bed: "King Bed",
        price: 590,
        breakfast: "Breakfast included",
        img: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400&q=80",
        badge: "",
      },
      {
        name: "Cliff Suite",
        size: "80 m²",
        view: "Panoramic Cliff",
        bed: "King + Terrace",
        price: 1100,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Spa Bath",
      "Smart TV",
      "Italian Espresso Set",
      "A/C",
      "Santa Maria Novella",
    ],
    hotelFacilities: [
      "Infinity Pool",
      "Private Beach",
      "Spa",
      "Cliffside Restaurant",
      "Aperitivo Bar",
      "Boat Rentals",
    ],
    nearbyPois: [
      { icon: "⛵", name: "Positano", time: "20 min by boat" },
      { icon: "🏛", name: "Ravello", time: "25 min by car" },
      { icon: "✈️", name: "Naples Airport", time: "60 min by car" },
    ],
    checkin: "From 3:00 PM",
    checkout: "Until 12:00 PM",
    reviewsList: [],
    scores: { cleanliness: 9.6, location: 9.7, service: 9.4, value: 9.1 },
  },
  {
    id: "maldives-bungalow",
    name: "Maldives Overwater Bungalow",
    location: "Maldives",
    locationSearch: "maldives",
    price: 820,
    stars: 5,
    rating: 9.8,
    ratingLabel: "Exceptional",
    reviews: 148,
    badge: "Exclusive",
    types: ["resort", "villa"],
    amenities: ["pool", "spa", "restaurant", "beach", "gym"],
    img: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=90",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=90",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=90",
    ],
    address: "North Malé Atoll, Republic of Maldives",
    description: [
      "Floating above the Indian Ocean in a turquoise lagoon, our overwater bungalows offer an unrivalled experience of solitude and luxury. Step directly into warm, crystal-clear waters from your own private deck.",
    ],
    rooms: [
      {
        name: "Lagoon Bungalow",
        size: "90 m²",
        view: "Lagoon",
        bed: "King Bed",
        price: 820,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=400&q=80",
        badge: "",
      },
      {
        name: "Ocean Villa",
        size: "150 m²",
        view: "Open Ocean",
        bed: "King + Pool",
        price: 1500,
        breakfast: "Full board + spa",
        img: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Outdoor Bathtub",
      "Glass Floor Panel",
      "Nespresso",
      "A/C",
      "Snorkel Gear",
      "Welcome Champagne",
    ],
    hotelFacilities: [
      "Infinity Pool",
      "Private Beach",
      "Overwater Spa",
      "Underwater Restaurant",
      "Diving Centre",
      "Seaplane Transfers",
    ],
    nearbyPois: [
      { icon: "🐠", name: "House Reef", time: "Steps away" },
      { icon: "🌊", name: "Dolphin Cruise", time: "Available daily" },
      { icon: "✈️", name: "Velana Airport", time: "25 min by seaplane" },
    ],
    checkin: "From 2:00 PM",
    checkout: "Until 12:00 PM",
    reviewsList: [],
    scores: { cleanliness: 9.9, location: 9.8, service: 9.7, value: 9.3 },
  },
  {
    id: "marrakech-riad",
    name: "Marrakech Riad Palace",
    location: "Marrakech, Morocco",
    locationSearch: "marrakech morocco",
    price: 195,
    stars: 4,
    rating: 8.9,
    ratingLabel: "Superb",
    reviews: 305,
    badge: "",
    types: ["boutique"],
    amenities: ["pool", "spa", "restaurant"],
    img: "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=1200&q=90",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=90",
    ],
    address: "Derb Sidi Ahmed Ou Moussa, Marrakech Medina, Morocco",
    description: [
      "Hidden within the labyrinthine medina of Marrakech, the Riad Palace is a jewel of Moorish architecture and sensory delight. Step through a modest wooden door and enter a world of geometric tilework, carved cedar ceilings, and perfumed rose gardens.",
    ],
    rooms: [
      {
        name: "Courtyard Room",
        size: "25 m²",
        view: "Courtyard",
        bed: "King Bed",
        price: 195,
        breakfast: "Breakfast included",
        img: "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=400&q=80",
        badge: "",
      },
      {
        name: "Rooftop Suite",
        size: "50 m²",
        view: "Medina Rooftop",
        bed: "King Bed",
        price: 360,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Hammam Bathroom",
      "Mint Tea Service",
      "A/C",
      "Argan Oil Toiletries",
      "Personal Butler",
    ],
    hotelFacilities: [
      "Central Pool",
      "Hammam Spa",
      "Moroccan Restaurant",
      "Rose Garden",
      "Souk Tours",
    ],
    nearbyPois: [
      { icon: "🕌", name: "Koutoubia Mosque", time: "10 min walk" },
      { icon: "🏛", name: "Bahia Palace", time: "12 min walk" },
      { icon: "✈️", name: "Marrakech Airport", time: "20 min by car" },
    ],
    checkin: "From 3:00 PM",
    checkout: "Until 12:00 PM",
    reviewsList: [],
    scores: { cleanliness: 9.0, location: 9.2, service: 8.8, value: 9.4 },
  },
  {
    id: "bali-eco-lodge",
    name: "Bali Jungle Eco Lodge",
    location: "Bali, Indonesia",
    locationSearch: "bali indonesia",
    price: 145,
    stars: 4,
    rating: 9.0,
    ratingLabel: "Superb",
    reviews: 178,
    badge: "Eco",
    types: ["eco", "retreat"],
    amenities: ["pool", "spa", "restaurant", "gym"],
    img: "https://images.unsplash.com/photo-1536625979259-e8d0d612f88d?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1536625979259-e8d0d612f88d?w=1200&q=90",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=90",
    ],
    address: "Jl. Bisma, Ubud, Gianyar, Bali 80571, Indonesia",
    description: [
      "Immersed in the lush jungle of Ubud, our eco lodge is a pioneer of sustainable luxury. Built entirely from reclaimed materials and powered by renewable energy, the lodge sits above a sacred river gorge — the sound of water your constant companion.",
    ],
    rooms: [
      {
        name: "Jungle Bungalow",
        size: "32 m²",
        view: "River Gorge",
        bed: "Queen Bed",
        price: 145,
        breakfast: "Breakfast included",
        img: "https://images.unsplash.com/photo-1536625979259-e8d0d612f88d?w=400&q=80",
        badge: "",
      },
      {
        name: "Treetop Villa",
        size: "65 m²",
        view: "Jungle Canopy",
        bed: "King + Hammock Deck",
        price: 280,
        breakfast: "Full board",
        img: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Open-air Shower",
      "Balinese Tea",
      "Natural Ventilation",
      "Organic Toiletries",
      "🦎 Wildlife Guide",
    ],
    hotelFacilities: [
      "Natural Pool",
      "Ayurvedic Spa",
      "Farm-to-Table Restaurant",
      "Yoga Pavilion",
      "E-Bike Rental",
    ],
    nearbyPois: [
      { icon: "🌾", name: "Tegallalang Rice Terrace", time: "20 min by bike" },
      { icon: "🐒", name: "Monkey Forest", time: "15 min walk" },
      { icon: "✈️", name: "Ngurah Rai Airport", time: "60 min by car" },
    ],
    checkin: "From 2:00 PM",
    checkout: "Until 11:00 AM",
    reviewsList: [],
    scores: { cleanliness: 9.2, location: 8.8, service: 9.0, value: 9.6 },
  },
  {
    id: "swiss-alpine",
    name: "Swiss Alpine Chalet",
    location: "Zermatt, Switzerland",
    locationSearch: "zermatt switzerland",
    price: 385,
    stars: 5,
    rating: 9.3,
    ratingLabel: "Exceptional",
    reviews: 92,
    badge: "",
    types: ["boutique", "resort"],
    amenities: ["spa", "restaurant", "gym"],
    img: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800&q=90",
    gallery: [
      "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=1200&q=90",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=90",
    ],
    address: "Bahnhofstrasse 22, 3920 Zermatt, Switzerland",
    description: [
      "Situated car-free at 1,620m altitude with direct views of the Matterhorn, the Swiss Alpine Chalet is the quintessential mountain sanctuary. Stone, timber and wool create an atmosphere of cosy, alpine authenticity.",
    ],
    rooms: [
      {
        name: "Alpine Room",
        size: "30 m²",
        view: "Matterhorn View",
        bed: "Twin or King",
        price: 385,
        breakfast: "Breakfast included",
        img: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=400&q=80",
        badge: "",
      },
      {
        name: "Summit Suite",
        size: "70 m²",
        view: "Panoramic Matterhorn",
        bed: "King + Fireplace",
        price: 720,
        breakfast: "Half board",
        img: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400&q=80",
        badge: "Best Value",
      },
    ],
    roomAmenities: [
      "Sauna",
      "Smart TV",
      "Swiss Coffee Maker",
      "Fireplace",
      "Weleda Toiletries",
      "Ski Storage",
    ],
    hotelFacilities: [
      "Alpine Spa",
      "Fondue Restaurant",
      "Fitness Centre",
      "Ski-in/Ski-out",
      "Sledge Hire",
    ],
    nearbyPois: [
      { icon: "🏔", name: "Matterhorn Glacier", time: "20 min by cable car" },
      { icon: "⛷", name: "Zermatt Ski Area", time: "Steps away" },
      { icon: "🚂", name: "Zermatt Station", time: "5 min walk" },
    ],
    checkin: "From 3:00 PM",
    checkout: "Until 11:00 AM",
    reviewsList: [],
    scores: { cleanliness: 9.5, location: 9.6, service: 9.2, value: 8.9 },
  },
];
